### ISSUE TITLE
Meeting with HRS Summer Team

### ISSUE THREAD

**Issue by janakshah373** [AguaClara/Fluoride-Auto#68]
Hi Hannah, 

Could our team meet with you sometime this week or the next regarding some of your results this summer?

**Comment by HannahSi** [comment]
Meeting has been scheduled for 4:30 next Monday!

**Comment by HannahSi** [comment]
Hi Fluoride,

I just uploaded pictures to the HRS repository of the wooden prototype for the improved bottom geometry we designed at the end the summer. We intended for the real sed tank bottom insert to be cut from a solid 1" PVC cylinder, not a block. I'll attach the pictures below (sorry they're sideways), but they can also be found in the high_rate_sedimentation repository > Images > Setup > Non-Converging Bottom Cutting Jig.jpg and Non-Converging Bottom Prototype.jpg

<img src="https://raw.githubusercontent.com/AguaClara/high_rate_sedimentation/master/Images/Setup/Non-Converging%20Bottom%20Cutting%20Jig.jpg" width=300> <img src="https://raw.githubusercontent.com/AguaClara/high_rate_sedimentation/master/Images/Setup/Non-Converging%20Bottom%20Prototype.jpg" width=300>
